apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workloadselector: postgres-db
