apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  template:
    spec:
      containers:
      - name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: dev-wordpress-mysql
