apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app
spec:
  template:
    spec:
      containers:
        - name: app
          envFrom:
          - configMapRef:
              name: python-flask-app-env
