apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: APP_STATUS
              value: prod
