apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
